# Generated by Django 2.2.7 on 2019-11-26 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBrewsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='water', editable=False, max_length=200)),
                ('batch_volume', models.DecimalField(decimal_places=2, max_digits=5)),
                ('boil_volume', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fermentable',
            name='adjunct',
        ),
        migrations.RemoveField(
            model_name='fermentable',
            name='grain',
        ),
        migrations.AddField(
            model_name='fermentable',
            name='grain_type',
            field=models.CharField(blank=True, choices=[('BM', 'Base Malt'), ('AJ', 'Adjunct'), ('ME', 'Malt Extract'), ('SM', 'Specialty Malt')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='fermentable',
            name='pounds',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='hop',
            name='boil_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hop',
            name='ibu',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='hop',
            name='ounces',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='hop',
            name='utilization',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='hop',
            name='alpha_acid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('target_og', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('original_gravity', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('final_gravity', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('abv', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ibu', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('notes', models.TextField()),
                ('fermentable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBrewsApp.Fermentable')),
                ('hop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyBrewsApp.Hop')),
                ('water', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBrewsApp.Water')),
                ('yeast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBrewsApp.Yeast')),
            ],
        ),
    ]
