# Generated by Django 2.2.7 on 2019-11-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBrewsApp', '0002_auto_20191125_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='brew_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
