# Generated by Django 2.2.7 on 2019-11-27 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBrewsApp', '0004_auto_20191126_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='fermentable',
            name='brewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyBrewsApp.Brewer'),
        ),
        migrations.AddField(
            model_name='hop',
            name='brewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyBrewsApp.Brewer'),
        ),
        migrations.AddField(
            model_name='water',
            name='brewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyBrewsApp.Brewer'),
        ),
        migrations.AddField(
            model_name='yeast',
            name='brewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyBrewsApp.Brewer'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='brewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyBrewsApp.Brewer'),
        ),
    ]
