# Generated by Django 2.2.7 on 2019-12-03 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBrewsApp', '0005_auto_20191126_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fermentable',
            name='pounds',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='fermentable',
        ),
        migrations.AddField(
            model_name='fermentable',
            name='ppg',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='yeast',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyBrewsApp.Yeast'),
        ),
        migrations.CreateModel(
            name='Grist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pounds', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('fermentable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBrewsApp.Fermentable')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='grist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyBrewsApp.Grist'),
            preserve_default=False,
        ),
    ]
