# Generated by Django 2.2.7 on 2019-12-05 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBrewsApp', '0006_auto_20191202_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='grist',
        ),
        migrations.AddField(
            model_name='fermentable',
            name='pounds',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fermentable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyBrewsApp.Fermentable'),
        ),
        migrations.DeleteModel(
            name='Grist',
        ),
    ]
