# Generated by Django 2.2.7 on 2019-12-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBrewsApp', '0008_auto_20191204_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='water',
            name='batch_volume',
        ),
        migrations.RemoveField(
            model_name='water',
            name='boil_volume',
        ),
        migrations.AddField(
            model_name='recipe',
            name='batch_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='boil_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='srm',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
