# Generated by Django 2.2.7 on 2019-12-06 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBrewsApp', '0009_auto_20191205_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='brew_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
