# Generated by Django 2.2.7 on 2019-12-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBrewsApp', '0010_auto_20191205_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hop',
            name='boil_time',
        ),
        migrations.RemoveField(
            model_name='hop',
            name='ibu',
        ),
        migrations.RemoveField(
            model_name='hop',
            name='ounces',
        ),
        migrations.RemoveField(
            model_name='hop',
            name='utilization',
        ),
        migrations.AddField(
            model_name='recipe',
            name='hop_boil_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='hop_ounces',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='recipe',
            name='utilization',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
    ]
