# Generated by Django 2.2.7 on 2019-12-06 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBrewsApp', '0011_auto_20191205_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='water',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyBrewsApp.Water'),
        ),
    ]
