# Generated by Django 2.2.7 on 2020-06-02 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBrewsApp', '0013_auto_20191205_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fermentable',
            name='grain_type',
        ),
        migrations.AddField(
            model_name='fermentable',
            name='pounds',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='grist',
            name='brewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyBrewsApp.Brewer'),
        ),
    ]
